<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lesson</title>
</head>
<body>
    <h1>ЗАГОЛОВОК</h1>
    <img src="images/moon.jpg" alt="moon" width="500" >
    <p>Lorem ipsum dolor sit,<b><i> amet consectetur adipisicing elit</b> <i> impedit soluta nihil.</i> Saepe maiores illo deserunt eius? Consequatur, dolores perspiciatis ipsa repellendus rerum autem cupiditate quia in unde, accusamus amet.</p>
<p> Lorem ipsum dolor, sit amet consectetur adipisicing elit. <u> Totam, tempora.</u></p>
<ol>
    <li>пункт ткста.... або вільний текст</li>
    <li>пункт ткста.... або вільний текст</li>
    <li>пункт ткста.... або вільний текст</li>
    <li>пункт ткста.... або вільний текст</li>
</ol>

</body>
</html>
 
